### ISSUE TITLE
Explain differences from standard TiddlyWiki

### ISSUE THREAD

**Issue by pmario** [nathanielknight/tiddly-wiki-server#1]
The readme mentions: 

>It should come with a slightly altered empty TiddlyWiki that includes an extra tiddler store (for saved tiddlers) 

What does this mean?. I can see the empty.html.template ... But there is no info what has been changed. 

From my point of view it shouldn't be needed at all. It would be nice if the server would work with a default wiki.

**Comment by nathanielknight** [comment]
The default wiki doesn't have the TiddlyWeb plugin that enables the API that this server implements, so a slightly different default tiddler is required.

The separate tiddly store I'm talking about here is a second `div` containing the skinny version of any tiddlers a user has created. The default tiddler loading code picks this up fine; there are no changes to the core tiddlywiki code. I did it this way because it's *much* easier to put the tiddlers in a separate store than it is to add them to the existing store where the core tiddlers live.

Does that make sense? It sounds like I should add some more explanation to the README.

**Comment by pmario** [comment]
So you are talking about this element in empty.html.template

```
<script class="tiddlywiki-tiddler-store" type="application/json">
@@TIDDLY-WIKI-SERVER-EXTRA-TIDDLERS-@@N41yzvgnloEcoiY0so8e2dlri4cbYopzw7D5K4XRO9I@@
</script>
```

What is the hash used for?

Are there more changes like this one?

We should be able to let the TW CLI produce that code with a different base-template, which would be much smaller. So every wiki can be "converted / prepared" to be used with the server. ...

**Comment by pmario** [comment]
>The separate tiddly store I'm talking about here is a second div containing the skinny version of any tiddlers a user has created. 

A DIV ... I couldn't find this one

**Comment by nathanielknight** [comment]
Argh, sorry, I mis-remembered. It's a `script` with class `tiddlywiki-tiddler-store` and type `application/json`. In the template it contains a long random string (`@@TIDDLY-WIKI-SERVER-EXTRA-TIDDLERS-@@N41yzvgnloEcoiY0so8e2dlri4cbYopzw7D5K4XRO9I@@`) that the server replaces with the appropriate JSON on initial page load.

**Comment by pmario** [comment]
And that's the only change?

**Comment by nathanielknight** [comment]
That and the addition of the TiddlyWeb plugin (which I did via the default plugin mechanism).

To migrate from a "vanilla" tiddlywiki you can use the built-in [import function](https://tiddlywiki.com/static/Importing%2520Tiddlers.html), though I'd definitely keep the originals as a backup until this project has seen a little more testing.

**Comment by pmario** [comment]
Yea. ... I'm more interested in Rust atm then in the TW server itself. One of the first things I saw, was the template. ... I think we should be able to create a "custom" template + a download button, that should prepare a default empty.html for your server. 

This `N41yzvgnloEcoiY0so8e2dlri4cbYopzw7D5K4XRO9I` can be just any random string, or is it needed by the "rust-server" from now on?

**Comment by pmario** [comment]
The other argument for the server is the 10MByte memory per instance, which IMO would be a much nicer fit for IOT devices than a full blown Node.js installation.

**Comment by nathanielknight** [comment]
There's a function in the server that `replace`s the target string with JSON for the relevant tiddlers. You should be able to open the `empty.html.template` file from the release package and make any changes you'd like to make.

**Comment by pmario** [comment]
>There's a function in the server that `replace`s the target string with JSON for the relevant tiddlers. You should be able to open the `empty.html.template` file from the release package and make any changes you'd like to make.

OK I see. What I was thinking about is, that the Node.js version, with which we build single file wikis should be able to create a template, that can be used by your server. ... eg: 

```
tiddlywiki ./myRustWiki --init server
... some more plugins are inclued using the tiddlywiki.info file
tiddlywiki ./myRustWiki --build rust-template
```

The result of the --build command will be the file eg: `./myRustWiki/output/custom-template.html`, which should contain everything the server needs. ...

**Comment by nathanielknight** [comment]
I considered including the base tiddlywiki in the binary, but it's several megabytes and my understanding is that it will be loaded into memory when the server is running. Including it would increase memory consumption by ~40%, so I'm hesitant to add it when it can be distributed separately.

**Comment by nathanielknight** [comment]
I realized how to do this: an "initialization binary" distributed alongside the server. That binary shouldn't be long-running, so it can embed the default template no problem. It's also an obvious place to do "initial setup" like deciding on a username.

**Comment by nathanielknight** [comment]
Reading this more carefully, I see that what you want is actually inter-operating with vanilla (or vanilla-ish) tiddly wikis (i.e. ones generated using the NodeJS version of TiddlyWiki. I'm not sure how I'd do that correctly without including an XML parser in the library, and I *think* the use-case is covered by using the import function, so if I do add this feature it won't be for a while.

I've added some more details about how the template differs from "stock" TiddlyWikis; let me know if you have any more questions.
