### ISSUE TITLE
Docker?

### ISSUE THREAD

**Issue by poblabs** [nathanielknight/tiddly-wiki-server#14]
I'm pretty curious to try this out, but I don't know Rust at all. Any chance you could create a Dockerfile for the project?

**Comment by SurajRaika** [comment]
I know Rust so I thought why not learn about Docker and create a Docker file for this project. But is it just me or are Docker Desktop and vmmem using up a ton of resources?

**Comment by poblabs** [comment]
I'm not sure about Docker desktop. I use it on Ubuntu server and it seems pretty good on resources

**Comment by nathanielknight** [comment]
Next steps are:

- [x] Better optimize the Dockerfile (following, for example, [this guide](https://depot.dev/blog/rust-dockerfile-best-practices)).
- [x] Publish the image to dockerhub (or similar)
- [ ] Write a `docker-compose.yml` file for easier deployment

**Comment by nathanielknight** [comment]
Instructions for publishing a docker image to ghcr.io:

https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-docker-images#publishing-images-to-github-packages

**Comment by nathanielknight** [comment]
With the above changes, releases now trigger a Docker image to be published to ghcr.io.

All that remains is:

- [x] Instructions for running in Docker (prominently displayed in the README), and
- [x] A `docker-compose.yml` file for easy deployment.

**Comment by nathanielknight** [comment]
The remaining points on this issue are addressed by #30. The Docker Compose file won't actually work until I release v0.3.0, which I'm planning to do shortly.
