### ISSUE TITLE
Stream the full Wiki?

### ISSUE THREAD

**Issue by nathanielknight** [nathanielknight/tiddly-wiki-server#5]
On first page load this server sends the whole TiddlyWiki bundle as well as all of the user's tiddlers. This means allocating several megabtyes of memory (which might not be relinquished to the OS). I'd be interested in the performance a solution that streams the response without loading it all into memory.

**Comment by linonetwo** [comment]
lazy all experience?

**Comment by nathanielknight** [comment]
It's also worth embedding the "empty" wiki in the binary. The empty wiki is about 2MB, and while that's a substantial addition to the binary (which is about 8MB at time of writing) the result is still a small fraction of the NodeJS binary, so it's still fulfilling its purpose as "memory efficient tiddlywiki backend".

**Comment by nathanielknight** [comment]
#29  obsoletes this issue
