### ISSUE TITLE
release npm package

### ISSUE THREAD

**Issue by linonetwo** [nathanielknight/tiddly-wiki-server#8]
Using napi binding or something. So it can be used in https://github.com/tiddly-gittly/TidGi-Desktop 

But as long as this can handle reading nodejs wiki's file from filesystem.

**Comment by nathanielknight** [comment]
Unfortunately `tiddly-wiki-server` stores the wiki in a different format (as JSON tiddlers in a SQLite database), so it's not compatible with the first-party file format that the NodeJS version uses.

**Comment by linonetwo** [comment]
Okay, I don't have an urgent need for this. If I need one I will reference your code.

**Comment by nathanielknight** [comment]
Sounds good. Sorry I can’t be more help!

**Comment by linonetwo** [comment]
I see https://tiddlywiki.com/#TiddlyWeb today. Does this mean nathanielknight/tiddly-wiki-server can be used to create a TiddlyWeb service?

Or a tiddlyhost that can lazy load and fine grain save? (Tiddlyhost currently seem to load full 10M+ wiki and save 10M+ on a single change)

**Comment by nathanielknight** [comment]
On first load load you have to load at least the TiddlyWiki JS (which is substantial), but my understanding is that subsequent edits would make only partial saves. I don't think the TiddlyWeb plugin does anything very sophisticated to prevent concurrent edits (and this project certainly doesn't) so it's probably not suitable for multi-user wikis.

**Comment by linonetwo** [comment]
I just wan't to implement single user use case, but with lazy load to speed up.
